name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 5

    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm run check

      - name: Test site
        run: pnpm run test

      - name: Build library
        id: build
        run: pnpm run build
